apiVersion: v1
kind: Secret
metadata:
  name: ipv64-api-key
  namespace: cert-manager
type: Opaque
stringData:
  IPV64_API_KEY: ENC[AES256_GCM,data:6zarVJJvu+FrZJaUSZEwXOtyv/agJoYWWVjjv5txAxs=,iv:RfyDrpevQVf/vSHvs5/Z8BOTW+MgXHbDfnN79nbD4bg=,tag:+LtPC1hIF2Kbm35KFyUzeg==,type:str]
sops:
  age:
    - recipient: age1ycyh0u3pvt39sucsd3jznl6ut4a4qz09f6wruqrl2565ddwhpd5qhrglw7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUaDVyNzNWaWJNZzZMY3hB
        STFwWTlTMVFqbW1LLytXUHJvZDRiMGpOTGdzCjdPU0psMWhoYjZiSVdwVERmVDl2
        d0xKMUkvbTloRU5Fd2NoaFVVWVB0TGMKLS0tIFcvUkZVNmxHeVlVRWR0c21jLzBL
        bWJMMjlkMVJQTk41bHNRZEdqZmNDZEkKhcH6YT7Vl9lmmrgFXZ+4/GCeQBLPqRi0
        Ok+8p7Sv2FS98zIk/W2kKSTaAcWKra1PwlxINXgIHxCdpFAdIEElNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-07T13:30:39Z"
  mac: ENC[AES256_GCM,data:LfUvjz0SvO6HKjuKctR1AflyePNAN+Y0vtqxPFhRkKj5u+2iMZN3mNcqQtX+7lMY9CjksP8uOuOOKMpocbUnhKcomnyUCwuHMBnMQyWtuOK8M4spWikTRJGr9Q44HKaMvMnGyS8ba3pFAd/ITu2FcEKrGbHN9y1Zdm6ZfScdTkU=,iv:8y8act84omehQNPqFEFOfeXG/pA1l5Y7+1B6/FC/gck=,tag:goRaF/ZdmP811qvjYeQRnQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
