---
cluster:
  # Provides cluster specific network configuration options.
  network:
    dnsDomain: cluster.local # The domain used by Kubernetes DNS.
    # The pod subnet CIDR.
    podSubnets:
      - 10.244.0.0/16
      - fd00:0:0:1::/64
    # The service subnet CIDR.
    serviceSubnets:
      - 10.96.0.0/12
      - fd00:0:0:0::/116
