# Kubernetes version
# This file is tracked by Renovate and serves as the source of truth for the Kubernetes version
#  When upgrading kubernetes, this version should match the image used in: talosctl upgrade-k8s --to <VERSION>
version: v1.35.2
