apiVersion: v1
kind: Secret
metadata:
  name: paperless-ngx
type: Opaque
stringData:
  PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:CxIoxsI=,iv:7w80NXM45SdrPbdte4UdkGXRBv11D+0HtXzCvMOCAfQ=,tag:wExVUjB96x8oZhwgwSHVPQ==,type:str]
  PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:P4CvGeo=,iv:a33XIUa8WlRUjtmc3pnqQwzvCbB4VsSGmdj7W4N9dP0=,tag:2v5DEMi9QipLIHJsteSUhw==,type:str]
sops:
  age:
    - recipient: age1ycyh0u3pvt39sucsd3jznl6ut4a4qz09f6wruqrl2565ddwhpd5qhrglw7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6YUU0SkNoWjUrMFBqYWhE
        cHlsUitBWW9qZDhQNEIvZFlvQ3VDeEF4T2hBCnNXYWloSjFyYlRkY0h0MCtWeXRo
        YUhhNFp1VmhFMTdDNzRNdHYvQm96ZzAKLS0tIC92UW5IaENKdWJQUy85WFdxSDBN
        SU9HeG9yQUFhRCtHNlBiOHA2SjFHZUEK42kzero2i6SpX85OInPIf95ptixLi8md
        lGYUvO/KQUhQmuC3GDjUtQwF4XL8Jh0qX9D6Y6CPtyVi2g0zOetKRg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-21T16:34:33Z"
  mac: ENC[AES256_GCM,data:KwNfDX4P/PeCTgjTdOE+j2CVxhPN9bUQLaDo2/vbAxvnnwL5IXcqgdlvaz/PsUdqg/+6PlDjq2S5o/Di6SWXN0RWo/T6xlTyk6e5GrGvEOZS+CXgfyDobe7sPC3qAN5bH8/qLnku+qQ5Gw74zX/YyGqw5kx+682ntZ9BGqajJ48=,iv:Iu6URL3HYYTX3yBVcH5HUwxd2GZ8c2BpD8w0sp0HOtc=,tag:0poOAMsyRQii0C3EpZs3wQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
