apiVersion: v1
kind: Secret
metadata:
  name: grafana-credentials
type: Opaque
stringData:
  admin-user: ENC[AES256_GCM,data:vtbMJOA=,iv:x0PZhlzy60cGxxQaud0JwRb8Yx1UfX01o78PetAmVSU=,tag:6Nu26wk7NEMe+3HcV4Xbew==,type:str]
  admin-password: ENC[AES256_GCM,data:DQ+iVc7WBu0=,iv:JccWJ1cV7g/mMsr4ok0Ij150HAUZzSfaOAnvYN+FP8s=,tag:NaE+gNR3BA9yOEvZM/70Jw==,type:str]
sops:
  age:
    - recipient: age1ycyh0u3pvt39sucsd3jznl6ut4a4qz09f6wruqrl2565ddwhpd5qhrglw7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVR2QxZllaUDFxUGkya25E
        TmY0cTFrM0t4T3BuVjhnSXhvWnMrdVdTV1VvCkhwSDZseUk2eHBma0xRTU5zMVZD
        TUhaTFBTd0FReTk2cmROaUlaNDd6R1EKLS0tIEFyWCtnRXRNT1hVOU5MZ3QzcWox
        ZnpWZmF0clpiQWpIQW40bEZpZUQxQUUKqNjX0tBqJNktOl41QddZdopHrqbYBfhe
        uKETtGRw6rYW3ioaRRtr2CMQ+a4fGFvJIuAkzbcG/fJS/pmUtxVsEQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-22T10:50:09Z"
  mac: ENC[AES256_GCM,data:AoR5RzUUndeKjBVK8HOxYxp8jGAsL3p8Kwp6obzSL5fqMbvwXL5K4E1KLJMIGHqEwntnHQe5BWAO3GazDhHW3PSxE331LX/HEIRNTTlndpv6SUgnpgAEUOS9wGLfRwcKtZoHxIRW24cJAkjO6rf16wPekxv7j8AKQWuofUafEq0=,iv:doarRfnnnoeeBi1UZgLY6mfjqg8W6aEvWfAbg6N8vdc=,tag:Gm4heD4tATchYHazrFimcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
