apiVersion: v1
kind: ConfigMap
metadata:
  name: blocky-config
  namespace: networking
  labels:
    app: blocky
data:
  config.yml: ENC[AES256_GCM,data:HSmXLdaXTXLMXcY0VMjUmZxqJvZrafl2mlhCSAn9TkLqLSoH2MIZYtMpkaFdOl2ubboRi5qiZXjphXbRyEP8o3Ml4mGEZJ9jApBFe4sCTJ23Uuv8cHotfoIo/lnx6ZuADXJA5HD6/+Q0sPOXsXYefLBHUuNTCHZE2jxciBBviBAx+EO27KY4X3QowHQwE1qHGW0elK6p6QFSQ+RsTklSJ+vx1Ex0QKL0tr7DdBa9EQFfvB1oqz0K1aTe9MBWM8Dn0iqX19IUIO/o36p/eByiJpOa4nku+HkSVNnZS+NvgZByvknbBhlRImw1bzVG4q00dKaBPksDj8I3pMEywz0sMjlCBxiPBg8kbqEW7QKfzcLjngvpiu+UxcTbBQ4KkjWwcpjYE3zjTLFe8cNSymqECwBk06dxq7g8SgYvCzi8PLYkzXsA6fBQnVSLTpEOKGeR77yYzvwZ+dWt2YcPx4V3ddilMFn8FlCiuCpay1TOr01ApHp/fKsZgFNnanAUJS7pJA3EyKmCQ32V2NmVx5L2D/IKpxRFiMa+LY1w9mR8yh67IWQwfz2Rq0jaKe4EGYtYI3UpBbqK4rop4sPvy/r1y83+6vGOPM22fS0IuGJ0GS/xvw12foTA3PZyeINXPR3wEbvGaVrIDDXXc9zVouDcjeupDaLZq0zT1RJ6hMGX4yoLleQ35CoEUHcfR5nRjPkiA1C9ovSy/DxTzz2y1JqCeFaqIhT0vWX08DrHVvHGB7sZQf+A/ltcPP5cfzLFEQSabIGmjSJSIdaebodsxOcVcusw2TDLMPxvk3NAoInw8DAPF3XjthwQSYrn+QA3mTl4DCvjKkFGhOvt+EJ3IHQRVQfEXluE2nrvq6VZrpktL07tch/K1kAYtxvl7k9SFXlA/PJz3qcT8d3zssXrkT9jNV4pF3c+zGohqsE/z3na7GJI7th2MPf5yuL/UFqZJOT+l7ubxH0krAIqo7fS9B3EbnyNGUios/WbnoyqxDuydQiIbtMDfk9nqeB+dMXdg3Y9p1uyYv7zRO08P7vSy7T25AsWJzaEaFp6k3i+yjEdmXsK0vUc07qx6XvdH9tKMDFMwYYX2IW76mRoiyJ1Kddph9FFixLUkbqNhmkkmn08zS/CSvDT1pHVtmuXRI37cyGkFAv70SWv7FXxpPRgq86sUn7Nd9e2Jhc6h4oAB2yOUUrEbggRAvDkp6pnqH7zx9GeU2QLiPPhpAiGfcsPseMhhy6iE93A9G/2m+EHSsBpNJoGODZ3c6AM+NJ5kcIDk2VNZYgIJ7G1L7bwVovqdl4e6w8v9dkRLMPCcEoU8a21FDuNHmCq+lQxqw79IsIhpbh9FvROuF3ro87JgfCa+xknnAXfs9I/KRpfO8XxCsDFslyLJCTpPqdiRoZA2UuLvc4xIi7i7AB1qBXhHK6hofg4kDG1jjpSCLU0H5QTkCldw1uNs9CxSMZvfHV4Di55oftyvEELyJWxGkd1lxYMnbfXeoXPQaGks06MyvdZ7cJQ4B6ITVPmru2vFkiirzJUkotXyrb7kvJrNERcg41G+FJhso66IaU/jsPoOWs2Vn3+ZmqGC6bHJTNDUGUf2ZVZnrfyOfMJX8pjMolyHmwzqBMQzB2EBzNvMccbylcFqgN4FTSvNqzyEd7eJgjRlk93HniDHKsYr7ZoCZeJbvUPc0ogJ/Gn117sEmE7vClPgMXiOigMEVNmbQ==,iv:PDoX3eS3RiawUSvnWZqTahBnNH5tVLab5rp6re4Zl2E=,tag:dxZytmQlWHfWi+qzda6gDA==,type:str]
sops:
  age:
    - recipient: age1ycyh0u3pvt39sucsd3jznl6ut4a4qz09f6wruqrl2565ddwhpd5qhrglw7
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzY2x1cGRiclRMZFRQQlVZ
        TURPSVpqQ2lLRnJXenNtRHpWMHJrVGJYQUUwCnZxaDh0ODIrZkZjekVYQ2lod3lU
        bGFTU0FvVmhEYWRBVzBCOU83RHFteFUKLS0tIFBMTXdpVmhsSU9jMG1LcXhybTRO
        RUdJdUFZMHUrWHNqYldkNWRRSmFYaEkKRmAp5D55F6zc+euf+35j5Ugwb1gCBiOQ
        zlcIqTdnGw1rbH3eqHFwKf67WwSC03e6avQpwjectOa9G5M5CyTloQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-01-25T14:50:28Z"
  mac: ENC[AES256_GCM,data:HeVZ2JxqqvlzjbBaJJMR5zH74iIAgxxTWdChvzRve+LEBfalMYEDZKsSiVM2e2payBJ5Erk+pO6cJ3qmTAQVoMHrhYhH2jEOwzI16QsLGiDiZfKU34wJaa0uqE8GGZT/Klf6niztiEkMcqMK+Ndgn1OpttwHAGiROzMlG36EYWg=,iv:m6/uEdMtIzjRC74m+MCGm81jMGxwD9uPhNDCqS3PtqU=,tag:aua5I6BAhSdA/MFOUu6rpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
