apiVersion: apps/v1
kind: Deployment
metadata:
  name: blocky
  labels:
    app: blocky
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blocky
  template:
    metadata:
      labels:
        app: blocky
    spec:
      automountServiceAccountToken: false
      containers:
        - name: blocky
          image: spx01/blocky:v0.29.0
          ports:
            - name: dnstcp
              containerPort: 53
              protocol: TCP
            - name: dnsudp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 4000
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - /app/blocky
                - healthcheck
            initialDelaySeconds: 15
            periodSeconds: 10
          volumeMounts:
            - name: blocky-config
              mountPath: /app/config.yml
              readOnly: true
              subPath: config.yml
          resources:
            requests:
              cpu: 400m
              memory: 509Mi
              ephemeral-storage: 500Mi
            limits:
              memory: 509Mi
              ephemeral-storage: 1Gi
#          securityContext:
#            capabilities:
#              add:
#                - NET_BIND_SERVICE
#              drop:
#                - ALL
      volumes:
        - name: blocky-config
          configMap:
            name: blocky-config
            optional: false
