apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cert-manager-lego-webhook
  namespace: cert-manager
spec:
  url: https://yxwuxuanl.github.io/cert-manager-lego-webhook/
  interval: 6h
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager-lego-webhook
  namespace: cert-manager
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 30m
  chart:
    spec:
      chart: cert-manager-lego-webhook
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager-lego-webhook
        namespace: cert-manager
      interval: 6h
  valuesFrom:
    - kind: ConfigMap
      name: cert-manager-lego-webhook-helm-values
